apiVersion: v1
entries:
  app1:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-29T15:51:18.930863+05:30"
    description: A Helm chart for Kubernetes
    digest: 2fe36946914a893ed1d475da3d11172d4b934af34ec1a6bdca3d6f64b898fc7c
    name: app1
    urls:
    - https://gvasanka.github.io/jmeter-helm-chart/app1-0.1.0.tgz
    version: 0.1.0
generated: "2020-04-29T15:51:18.930348+05:30"
