# Default values for distributed-jmeter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

master:
  ## The number of pods in the master deployment
  replicaCount: 1

server:
  ## The number of pods in the server deployment
  replicaCount: 1

image:
  ## Specify an imagePullPolicy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  pullPolicy: IfNotPresent

  ## The repository and image
  ## ref: https://hub.docker.com/r/pedrocesarti/jmeter-docker/
  repository: "pedrocesarti/jmeter-docker"

  ## The tag for the image
  ## ref: https://hub.docker.com/r/pedrocesarti/jmeter-docker/tags/
  tag: 3.3

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi

jmeter:
  xms:
    memory: 100m
    #  Xms<size>        set initial Java heap size
  xmx:
    memory: 100m
    #  Xmx<size>        set maximum Java heap size