# JMete slave pod deployment default values

# POD related configuration
pod:
  # The number of JMete slave pods required
  replicaCount: 1

# POD resource configuration
resources:
    limits:
      cpu: 500m
      memory: 2560Mi
    requests:
      cpu: 300m
      memory: 2048Mi

# POD image configuration
image:
  repository: gvasanka/jmeter-plugins-slave
  tag: 5.1.1
  pullPolicy: IfNotPresent

# JMeter JVM memory configuration
jmeter:
  xms:
    #  Xms<size>        set initial Java heap size
    memory: 1536M
  xmx:
    #  Xmx<size>        set maximum Java heap size
    memory: 2048M
